### ISSUE TITLE
What do each of the label types do?

### ISSUE THREAD

**Issue by rostero1** [kjy00302/niimprint#2]
I see there are 100s of label types on the product page.  What types 1-3 map to?

**Comment by kjy00302** [comment]
Actually, there are more than 3 types.

1. Standard label paper
2. Sense marked label paper
3. Continuous label paper
4. ? (referenced as GAP_HOLD in internal code)
5. Transparent label paper

**Comment by rostero1** [comment]
Thanks a lot.  Also, it's impressive how you put this project together.
